package com.worldmap.recommendation.application;

import com.worldmap.recommendation.domain.RecommendationSurveyAnswers;
import java.util.List;

final class RecommendationOfflinePersonaFixtures {

	private RecommendationOfflinePersonaFixtures() {
	}

	static List<RecommendationOfflinePersonaScenario> scenarios() {
		return List.of(
			scenario("P01", "따뜻한 기후와 빠른 도시 리듬, 영어 환경을 함께 원하는 디지털 노마드",
				RecommendationSurveyAnswers.ClimatePreference.WARM,
				RecommendationSurveyAnswers.PacePreference.FAST,
				RecommendationSurveyAnswers.BudgetPreference.HIGH,
				RecommendationSurveyAnswers.EnvironmentPreference.CITY,
				RecommendationSurveyAnswers.EnglishImportance.HIGH,
				RecommendationSurveyAnswers.PriorityFocus.DIVERSITY,
				List.of("싱가포르", "아랍에미리트", "미국"), "4~5점"),
			scenario("P02", "생활비를 아끼면서도 음식과 다문화 환경을 선호하는 초보 이민 관심자",
				RecommendationSurveyAnswers.ClimatePreference.WARM,
				RecommendationSurveyAnswers.PacePreference.BALANCED,
				RecommendationSurveyAnswers.BudgetPreference.LOW,
				RecommendationSurveyAnswers.EnvironmentPreference.MIXED,
				RecommendationSurveyAnswers.EnglishImportance.MEDIUM,
				RecommendationSurveyAnswers.PriorityFocus.FOOD,
				List.of("말레이시아", "태국", "멕시코"), "4~5점"),
			scenario("P03", "조용하고 안전한 북유럽형 생활을 선호하는 안정 중시형",
				RecommendationSurveyAnswers.ClimatePreference.COLD,
				RecommendationSurveyAnswers.PacePreference.RELAXED,
				RecommendationSurveyAnswers.BudgetPreference.HIGH,
				RecommendationSurveyAnswers.EnvironmentPreference.NATURE,
				RecommendationSurveyAnswers.EnglishImportance.HIGH,
				RecommendationSurveyAnswers.PriorityFocus.SAFETY,
				List.of("노르웨이", "핀란드", "스웨덴"), "4~5점"),
			scenario("P04", "복지와 균형 잡힌 도시 생활을 원하는 중도 성향 직장인",
				RecommendationSurveyAnswers.ClimatePreference.MILD,
				RecommendationSurveyAnswers.PacePreference.BALANCED,
				RecommendationSurveyAnswers.BudgetPreference.MEDIUM,
				RecommendationSurveyAnswers.EnvironmentPreference.MIXED,
				RecommendationSurveyAnswers.EnglishImportance.MEDIUM,
				RecommendationSurveyAnswers.PriorityFocus.WELFARE,
				List.of("독일", "덴마크", "캐나다"), "4~5점"),
			scenario("P05", "영어가 매우 중요하고, 도시 활동성과 문화 다양성을 최우선으로 보는 인턴 준비생",
				RecommendationSurveyAnswers.ClimatePreference.WARM,
				RecommendationSurveyAnswers.PacePreference.FAST,
				RecommendationSurveyAnswers.BudgetPreference.HIGH,
				RecommendationSurveyAnswers.EnvironmentPreference.CITY,
				RecommendationSurveyAnswers.EnglishImportance.HIGH,
				RecommendationSurveyAnswers.PriorityFocus.DIVERSITY,
				List.of("미국", "캐나다", "영국"), "4~5점"),
			scenario("P06", "비슷한 기후라도 너무 비싸지 않은 나라를 찾는 현실형 사용자",
				RecommendationSurveyAnswers.ClimatePreference.MILD,
				RecommendationSurveyAnswers.PacePreference.BALANCED,
				RecommendationSurveyAnswers.BudgetPreference.LOW,
				RecommendationSurveyAnswers.EnvironmentPreference.MIXED,
				RecommendationSurveyAnswers.EnglishImportance.MEDIUM,
				RecommendationSurveyAnswers.PriorityFocus.SAFETY,
				List.of("포르투갈", "스페인", "체코"), "3~4점"),
			scenario("P07", "음식과 도시 속도가 중요하고, 아시아권 대도시를 선호하는 사용자",
				RecommendationSurveyAnswers.ClimatePreference.WARM,
				RecommendationSurveyAnswers.PacePreference.FAST,
				RecommendationSurveyAnswers.BudgetPreference.MEDIUM,
				RecommendationSurveyAnswers.EnvironmentPreference.CITY,
				RecommendationSurveyAnswers.EnglishImportance.LOW,
				RecommendationSurveyAnswers.PriorityFocus.FOOD,
				List.of("일본", "대한민국", "싱가포르"), "4~5점"),
			scenario("P08", "자연과 여유를 좋아하고, 영어는 있으면 좋지만 절대 기준은 아닌 사용자",
				RecommendationSurveyAnswers.ClimatePreference.COLD,
				RecommendationSurveyAnswers.PacePreference.RELAXED,
				RecommendationSurveyAnswers.BudgetPreference.MEDIUM,
				RecommendationSurveyAnswers.EnvironmentPreference.NATURE,
				RecommendationSurveyAnswers.EnglishImportance.MEDIUM,
				RecommendationSurveyAnswers.PriorityFocus.SAFETY,
				List.of("뉴질랜드", "캐나다", "스웨덴"), "4~5점"),
			scenario("P09", "따뜻한 기후와 높은 물가 허용으로 인프라와 안정성을 우선하는 사용자",
				RecommendationSurveyAnswers.ClimatePreference.WARM,
				RecommendationSurveyAnswers.PacePreference.BALANCED,
				RecommendationSurveyAnswers.BudgetPreference.HIGH,
				RecommendationSurveyAnswers.EnvironmentPreference.CITY,
				RecommendationSurveyAnswers.EnglishImportance.HIGH,
				RecommendationSurveyAnswers.PriorityFocus.WELFARE,
				List.of("아랍에미리트", "싱가포르", "호주"), "4~5점"),
			scenario("P10", "영어 친화도는 낮아도 괜찮고, 문화 다양성과 활기만 있으면 되는 사용자",
				RecommendationSurveyAnswers.ClimatePreference.MILD,
				RecommendationSurveyAnswers.PacePreference.FAST,
				RecommendationSurveyAnswers.BudgetPreference.MEDIUM,
				RecommendationSurveyAnswers.EnvironmentPreference.CITY,
				RecommendationSurveyAnswers.EnglishImportance.LOW,
				RecommendationSurveyAnswers.PriorityFocus.DIVERSITY,
				List.of("미국", "멕시코", "브라질"), "3~4점"),
			scenario("P11", "치안과 복지를 강하게 보고, 도시와 자연의 균형도 원하는 가족형 사용자",
				RecommendationSurveyAnswers.ClimatePreference.MILD,
				RecommendationSurveyAnswers.PacePreference.BALANCED,
				RecommendationSurveyAnswers.BudgetPreference.HIGH,
				RecommendationSurveyAnswers.EnvironmentPreference.MIXED,
				RecommendationSurveyAnswers.EnglishImportance.HIGH,
				RecommendationSurveyAnswers.PriorityFocus.SAFETY,
				List.of("캐나다", "덴마크", "네덜란드"), "4~5점"),
			scenario("P12", "물가가 낮아야 하고, 느긋한 생활과 자연이 중요한 장기 체류 관심자",
				RecommendationSurveyAnswers.ClimatePreference.WARM,
				RecommendationSurveyAnswers.PacePreference.RELAXED,
				RecommendationSurveyAnswers.BudgetPreference.LOW,
				RecommendationSurveyAnswers.EnvironmentPreference.NATURE,
				RecommendationSurveyAnswers.EnglishImportance.MEDIUM,
				RecommendationSurveyAnswers.PriorityFocus.SAFETY,
				List.of("포르투갈", "우루과이", "뉴질랜드"), "3~4점"),
			scenario("P13", "빠른 도시 환경과 다문화 경험을 원하지만 너무 더운 기후는 싫어하는 사용자",
				RecommendationSurveyAnswers.ClimatePreference.MILD,
				RecommendationSurveyAnswers.PacePreference.FAST,
				RecommendationSurveyAnswers.BudgetPreference.HIGH,
				RecommendationSurveyAnswers.EnvironmentPreference.CITY,
				RecommendationSurveyAnswers.EnglishImportance.HIGH,
				RecommendationSurveyAnswers.PriorityFocus.DIVERSITY,
				List.of("영국", "캐나다", "네덜란드"), "4~5점"),
			scenario("P14", "아시아권에서 생활비와 편의성 균형을 찾는 실용형 사용자",
				RecommendationSurveyAnswers.ClimatePreference.WARM,
				RecommendationSurveyAnswers.PacePreference.BALANCED,
				RecommendationSurveyAnswers.BudgetPreference.LOW,
				RecommendationSurveyAnswers.EnvironmentPreference.MIXED,
				RecommendationSurveyAnswers.EnglishImportance.MEDIUM,
				RecommendationSurveyAnswers.PriorityFocus.WELFARE,
				List.of("말레이시아", "태국", "베트남"), "4~5점")
		);
	}

	private static RecommendationOfflinePersonaScenario scenario(
		String id,
		String description,
		RecommendationSurveyAnswers.ClimatePreference climatePreference,
		RecommendationSurveyAnswers.PacePreference pacePreference,
		RecommendationSurveyAnswers.BudgetPreference budgetPreference,
		RecommendationSurveyAnswers.EnvironmentPreference environmentPreference,
		RecommendationSurveyAnswers.EnglishImportance englishImportance,
		RecommendationSurveyAnswers.PriorityFocus priorityFocus,
		List<String> expectedCandidates,
		String expectedSatisfactionRange
	) {
		return new RecommendationOfflinePersonaScenario(
			id,
			description,
			new RecommendationSurveyAnswers(
				climatePreference,
				pacePreference,
				budgetPreference,
				environmentPreference,
				englishImportance,
				priorityFocus
			),
			expectedCandidates,
			expectedSatisfactionRange
		);
	}
}
